chore(deps): update dependency centralized-templates to v30
pleo-io/danger-config pull request #62
Opened 2023-10-11 16:23 UTC by pleo-bot-renovate

This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [centralized-templates](https://togithub.com/pleo-io/centralized-templates) | major | `v28.1.0` -> `v30.0.0` |

---

### Release Notes

<details>
<summary>pleo-io/centralized-templates (centralized-templates)</summary>

### [`v30.0.0`](https://togithub.com/pleo-io/centralized-templates/releases/tag/v30.0.0)

[Compare Source](https://togithub.com/pleo-io/centralized-templates/compare/v29.0.1...v30.0.0)

##### Release Notes

##### Revert step name change ([#&#8203;960](https://togithub.com/pleo-io/centralized-templates/pull/960))

This PR reverts the name change to `build`, as it is required in many repos and the change of name blocks them.

***

##### 💥 Major changes

-   Feature/devx 1652 merging prs with only config changes for moons is blocked [#&#8203;953](https://togithub.com/pleo-io/centralized-templates/pull/953) ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))

##### 🐞 Fixes

-   Feature/devx 1687 have build step [#&#8203;962](https://togithub.com/pleo-io/centralized-templates/pull/962) ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))
-   Revert step name change [#&#8203;960](https://togithub.com/pleo-io/centralized-templates/pull/960) ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))

##### Authors: 1

-   Marcos Arranz ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))

### [`v29.0.1`](https://togithub.com/pleo-io/centralized-templates/blob/HEAD/CHANGELOG.md#v2901-Wed-Oct-11-2023)

[Compare Source](https://togithub.com/pleo-io/centralized-templates/compare/v29.0.0...v29.0.1)

##### Release Notes

##### Revert step name change ([#&#8203;960](https://togithub.com/pleo-io/centralized-templates/pull/960))

This PR reverts the name change to `build`, as it is required in many repos and the change of name blocks them.

***

##### 🐞 Fixes

-   Revert step name change [#&#8203;960](https://togithub.com/pleo-io/centralized-templates/pull/960) ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))

##### Authors: 1

-   Marcos Arranz ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))

***

### [`v29.0.0`](https://togithub.com/pleo-io/centralized-templates/blob/HEAD/CHANGELOG.md#v2900-Wed-Oct-11-2023)

[Compare Source](https://togithub.com/pleo-io/centralized-templates/compare/v28.2.0...v29.0.0)

##### Release Notes

##### Revert step name change ([#&#8203;960](https://togithub.com/pleo-io/centralized-templates/pull/960))

This PR reverts the name change to `build`, as it is required in many repos and the change of name blocks them.

***

##### 💥 Major changes

-   Feature/devx 1652 merging prs with only config changes for moons is blocked [#&#8203;953](https://togithub.com/pleo-io/centralized-templates/pull/953) ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))

##### 🐞 Fixes

-   Feature/devx 1687 have build step [#&#8203;962](https://togithub.com/pleo-io/centralized-templates/pull/962) ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))
-   Revert step name change [#&#8203;960](https://togithub.com/pleo-io/centralized-templates/pull/960) ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))

##### Authors: 1

-   Marcos Arranz ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))

***

### [`v28.2.0`](https://togithub.com/pleo-io/centralized-templates/blob/HEAD/CHANGELOG.md#v2820-Tue-Oct-10-2023)

[Compare Source](https://togithub.com/pleo-io/centralized-templates/compare/v28.1.0...v28.2.0)

##### Release Notes

##### feat(adding dev_deploy and dev_deploy_revert Github Action workflows) ([#&#8203;915](https://togithub.com/pleo-io/centralized-templates/pull/915))

Let's say I make a change to Hydra that has a downstream effect on Calypso. There's no way to test this properly in feature environments as there's no outgoing communication from a feature env. This is a blind spot in our testing environments.

This PR aims to address this. In this PR are two workflows which allow developers to deploy their version of a service directly into product-dev WITHOUT merging it.

##### `dev_deploy`

They can simply tag their PR with `dev-deploy` and the job will package their service into a docker image, push to ECR and then push the image tag into k8s/product-dev/application-moon_name.yaml where Helm will pick it up and deploy it into the cluster.

Note that we also check if there has already been a dev image built so we don't build unnecessary images. Why? Let's say I deploy my version into product-dev but then someone else merges a PR. I want to continue testing my changes so I need to run the `dev_deploy` job again, but the image already exists. No need to create a new one.

##### `dev_deploy_revert`

In this workflow, we get the last non-dev image tag pushed to AWS ECR and push that into the Helm release file. Note that we can't simply take the last commit hash of the repo as that does not necessarily correlate with the ECR image tag.

This workflow allows developers to revert their changes to product-dev, in the case that they break something or otherwise want to return product-dev to a clean environment

##### How was this tested?

It was tested on auxo moon by adding a new workflow directly in the moon repo. You can check the commit [history](https://togithub.com/pleo-io/auxo/commits/main) to see how the changes work, or reach out to me and I can walk you through how to check it.

##### update codeowners to infrastructure-core ([#&#8203;952](https://togithub.com/pleo-io/centralized-templates/pull/952))

***

##### 🎁 Features

-   feat(adding dev_deploy and dev_deploy_revert Github Action workflows) [#&#8203;915](https://togithub.com/pleo-io/centralized-templates/pull/915) ([@&#8203;paulosullivan22](https://togithub.com/paulosullivan22))

##### 🏠 Internal

-   update codeowners to infrastructure-core [#&#8203;952](https://togithub.com/pleo-io/centralized-templates/pull/952) ([@&#8203;dorsradek](https://togithub.com/dorsradek))
-   chore(deps): update aws-actions/amazon-ecr-login action to v2 [#&#8203;948](https://togithub.com/pleo-io/centralized-templates/pull/948) ([@&#8203;pleo-bot-renovate](https://togithub.com/pleo-bot-renovate) [@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))

##### Authors: 4

-   Marcos Arranz ([@&#8203;marcos-arranz](https://togithub.com/marcos-arranz))
-   Paul O'Sullivan ([@&#8203;paulosullivan22](https://togithub.com/paulosullivan22))
-   Radek Dors ([@&#8203;dorsradek](https://togithub.com/dorsradek))
-   Renovate (Pleo) ([@&#8203;pleo-bot-renovate](https://togithub.com/pleo-bot-renovate))

***

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - "after 8am and before 5pm every weekday" in timezone CET.

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

2023-10-13 09:22 UTC, dpotyralski approved these changes

2023-11-01 21:00 UTC, Niceplace commented
So, the failing check is a bit weird but it seems like dangerjs only works when a `pull_request` event is sent. I tested it here: https://github.com/pleo-io/danger-config/actions/runs/6725023185/job/18278544813?pr=64

There's an issue in the dangers repo that explains the same thing: https://github.com/danger/danger-js/issues/1310#issuecomment-1266780349

2023-11-02 02:37 UTC, Niceplace requested changes
Blocking this because I experimented with it and did not have time to revert my changes yet

2023-11-09 14:28 UTC, Niceplace approved these changes

2023-11-10 08:36 UTC, closed without merging

2023-11-13 08:14 UTC, dpotyralski commented
Since danger and therefore its config will most likely be dismissed soon, I've closed this PR.